---
language: node_js
node_js:
- '0.10'
cache:
  directories:
  - node_modules
before_install:
- |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      PR_FIRST=$(curl -s https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST}.patch | head -1 | grep -o -E '\b[0-9a-f]{40}\b' | tr -d '\n')
      TRAVIS_COMMIT_RANGE=$PR_FIRST^..$TRAVIS_COMMIT